- python/shotgun_fields/shotgun_field_manager.py
Minor bug fix that prevents from an init being called multiple times and thus registering the task manager multiple times with the shotgun globals module.
> Prevents init from happening multiple times

- python/shotgun_fields/shotgun_field_manager.py
Bubbled-field syntax is now handled by shotgun_globals.get_data_type natively.
> Removes specific handling of bubbled fields now that shotgunutils does.

- python/activity_stream/activity_stream.py
- python/activity_stream/data_manager.py
- python/activity_stream/dialog_reply.py
- python/activity_stream/widget_note.py
- python/note_input_widget/widget.py
This allows higher-level widgets to perform additional tasks or alter the resulting entity after it is created.
> #36162 Note/Reply entity creation is broadcast via an entity_created signal.

- python/activity_stream/activity_stream.py
- python/activity_stream/widget_new_item.py
- python/playback_label/playback_label.py
If not interactive, the play icon overlay will not be drawn, click events will not trigger playback signals, and the mouse icon won't be set to a finger pointer.
> PlaybackLabel can now be set to be non-interactive.

- python/activity_stream/activity_stream.py
- python/note_input_widget/widget.py
- python/shotgun_fields/bubble_widget.py
- python/shotgun_fields/entity_widget.py
- python/shotgun_fields/file_link_widget.py
- python/shotgun_fields/image_widget.py
- python/shotgun_fields/url_template_widget.py
This allows for a pre-submit callback to be attached to a NoteInputWidget. This can be used to do things like procedurally add attachments to the NoteInputWidget prior to the Note's or Reply's creation.
> Refactors how annotated frames are attached to Notes and Replies.

- python/activity_stream/activity_stream.py
- python/activity_stream/data_manager.py
- python/note_input_widget/__init__.py
- python/note_input_widget/dialog.py
- python/version_details/version_details.py
Plus access to note thread data as a property of activity stream and version details widgets.
> #36884: Signals passed up for note arrival and entity loading.

- python/activity_stream/activity_stream.py
- python/activity_stream/widget_note.py
- python/activity_stream/widget_reply.py
This is just a new configuration option for the activity stream widget. In the Shotgun Panel this is used to navigate to the User entity associated with the thumbnail, but in other applications of this widget we want to be able to disable that capability.
> #37270: Adds the ability to disable the clickable "hand" cursor on user thumbs.

- python/activity_stream/activity_stream.py
- python/activity_stream/widget_attachment_group.py
- python/activity_stream/widget_note.py
- python/version_details/version_details.py
Feature polish for SG3DR. Allows Note attachments to be filtered out of the attachment group widget based on a regex match against the attachment name. Also autoselects newly-created Notes if note selection is activated in the activity stream widget.
Bug fix: forces an sqlite cache update from SG when new attachments to a Note entity are made.
> #36274: Adds attachments filtering mechanism and new note autoselection.

- python/activity_stream/activity_stream.py
- python/note_input_widget/widget.py
This adds logic to the activity stream widget and note input widget to better handle the state when no project is available in the context (e.g. a "site" context).
Notes that are created require a project to be set and there are some cases when a project isn't available. Normally, we pull the project from the context but in the site context situation this is not an option. Instead, the note creation widget now tries to look for a project on the entity itself and if that fails in errors. The activity stream in turn hides the note input widgets in these cases.
> #37714 Improved activity stream note creation in site context

- python/version_details/shotgun_entities/card_widget.py
OrderedDict is requires Python 2.7 and therefore shouldn't be used in our frameworks.
> Replaced OrderedDict with a pure Python implementation of the same.

- python/activity_stream/activity_stream.py
https://jira.autodesk.com/browse/GAME-17158
In Dynamite, if the user started drawing with no version loaded, the new note panel was showing. It should only show if there is a version loaded to add a note to. This change early outs if that is the case.
> Do not show new note dialog if there is no current entity.

- python/version_details/version_details.py
Fixed misnamed variable and also call `destroy` on the `ActivityStreamWidget` so that it can stop its data manager.
This is dependent on https://github.com/shotgunsoftware/tk-framework-qtwidgets/pull/49 to work, but will not cause problems without it.
> Version details destroy function fixes.

- python/activity_stream/activity_stream.py
- python/activity_stream/widget_note.py
Fixes an issue where previously, if you replied to a note in the activity stream, you would see the note twice - once right at the top with the new reply and once further down without the reply. (it was only a temporary state, a UI refresh would make it go way). This change hides the note further down in the list, so that you only see the note once, first in the activity stream.
> #38223 No duplicate notes in activity stream

- framework.py
- python/__init__.py
- python/activity_stream/widget_activity_stream_base.py
- python/shotgun_fields/entity_widget.py
- python/shotgun_fields/file_link_widget.py
- python/shotgun_fields/url_template_widget.py
- python/utils.py
Makes use of sgtk.platform.get_hyperlink_html() when building url labels. The activity stream and shotgun_fields now use foreground colored, bold text for url labels.
**_NOTE:_** Pages other than the Activity Stream in the Shotgun Panel app remain unchanged. They make use of get_hyperlink_html, but they do so in a way that maintains their current styling.
> #38369: Hyperlink styling

- python/shotgun_menus/shotgun_menu.py
When the ability to type to highlight a menu item was added, it broke the default up/down arrow navigation. This PR allows the default behavior to work again.
> #39094 Fixes default key navigation in SG menu

- python/activity_stream/data_manager.py
The activity stream's `data_manager.destroy()` method was expecting a double underscore data retriever instead of single underscore. Guessing this was changed at some point and this was just missed. This was causing an exception on close when destroy was called on the activity stream. This change simply removes the extra underscore which fixes the problem.
> Remove extra underscores in data_manager destroy()

- python/activity_stream/widget_activity_stream_base.py
Remove early out from `_set_timestamp` so that it always sets the timestamp. If the created date is in the future, then use time now.
Nothing uses the return value of `_set_timestamp` so this should be a safe change.
> Handle time now is less than created time for widget time label.

- docs/index.rst
- docs/note_input_widget.rst
- docs/overlay_widget.rst
- docs/playback_label.rst
- docs/shotgun_fields.rst
- python/activity_stream/activity_stream.py
- python/activity_stream/widget_activity_stream_base.py
- python/shotgun_fields/entity_widget.py
- python/shotgun_fields/file_link_widget.py
- python/shotgun_fields/image_widget.py
- python/shotgun_fields/shotgun_field_delegate.py
- python/shotgun_fields/shotgun_field_manager.py
- python/shotgun_fields/url_template_widget.py
- python/version_details/version_details.py
* Adds a `ShotgunFieldDelegateGeneric` class that `ShotgunFieldDelegate` inherits from. The **Generic** class accepts a field data role to use for retrieving/setting data in the associated model. The `ShotgunFieldDelegate` class simply hard codes this to the role in the SG model.
* Added a manager method called `create_generic_delegate()` to make it easy for client code to create these delegates. The demo app example has been updated to use this new method:   https://github.com/shotgunsoftware/tk-multi-demo/commit/91468f
* fw docs were busted so this also includes a few tweaks to get rid of doc build errors outlined in internal ticket 40026
For reference, the original PR is here: https://github.com/shotgunsoftware/tk-framework-qtwidgets/pull/61
>  #38573 Second pass to create a field delegate for use with non-SG model

- python/activity_stream/activity_stream.py
- python/version_details/version_details.py
Part of the code exposing note selection by id to dynamite. This code is related to changes in https://github.com/shotgunsoftware/tk-multi-versiondetails/pull/19
The story related to this feature is: https://jira.autodesk.com/browse/GAME-10898
@AlexPapa1000 granted permission to merge these changes in as they were needed for the milestone completion of GAME-10989. Please review and any necessary fixes or issues from the review will be made retroactively
> Exposing note selection by ID to dynamite for GAME-10898

- python/activity_stream/activity_stream.py
The following reproduction steps revealed a strange bug with note selection in Dynamite:
1. Create two notes
2. Select the bottom note and add a reply
3. Select the other note (now at the bottom) and add a reply
Click back and forth in the notes and multiple times in the following areas:
Note that the notes will be improperly deselected or selected.
This problem was fixed by using the `underMouse` property instead of checking the rect.
> Use underMouse instead of rect contains to detect note selection.

- python/activity_stream/widget_note.py
This was a design change request made by Bill Bulman, in line with the future direction of the Shotgun website.
It adds a grey highlight border around the note:
> Make the border of the note match the border of the note input box.

- python/note_input_widget/widget.py
The Note's linked-to entity's created_by user is included in the Note's addressings_to.
> #40024: Properly populates addressings_to on new Note creation.

- python/activity_stream/activity_stream.py
- python/version_details/version_details.py
These changes originate from dynamite-lib pull request at https://github.com/shotgunsoftware/tk-framework-qtwidgets/pull/67
These changes are related to ticket https://jira.autodesk.com/browse/GAME-10898
It has an additional auto-scroll refinement that's not in the source PR above
Cherry-picked from dynamite lib commits 4947a423d7955b47ed19f1ae1d1016e6f01eb13e and 2dfb086fa6249ba27912d17ca729a9668dd901af
https://github.com/shotgunsoftware/tk-multi-versiondetails/pull/20 depends on the changes in this pull request
> Game-10898 expose note selection by ID

- info.yml
- python/activity_stream/activity_stream.py
- python/activity_stream/reply_list.py
- python/elided_label/elided_label.py
- python/version_details/shotgun_entities/card_widget.py
We're seeing a lot of problems related to garbage collection in PySide2/Qt5 when deleteLater is used. These issues result in crashes on DCC close in some cases, but also errors on app close even when the DCC isn't being closed.
> For #40555: Only calls deleteLater of Qt objects when in Qt4.

- python/models/hierarchical_filtering_proxy_model.py
* Fixed recursive searching for the case where an item reports having children, but hasn't loaded them yet, so the `rowCount` is 0 in the next recursion by ensuring the parent acceptance is never lost.
* Made the logic easier to understand.
> For #38483, edge case fix.

- python/screen_grab/screen_grab.py
Certain flavours of PySide2 can't access this static method from the class instance, so we'll invoke it directly.
> For #47053, screenshot tool fix

- python/overlay_widget/shotgun_overlay_widget.py
Refactored overlay widget into a QLabel so we can insert hyperlinks.
See [this PR](https://github.com/shotgunsoftware/tk-desktop/pull/96) to see it in action.
Here's a screenshot of the updated doc.
> For #46757, gentler error when `tank_name` is not set.

- python/activity_stream/activity_stream.py
- python/activity_stream/dialog_reply.py
- python/note_input_widget/widget.py
Fixes resource leaks where no task managers were passed to widgets, causing those widgets to allocate their own task managers and subsequent threads, causing issues with unclean shutdown and resource creep/leaking.
Big shoutout and thanks to @akitisa-epic for reporting and submitting these!
> SG-6701 Fixes task managers leaking

- python/activity_stream/activity_stream.py
We've been experiencing stability issues with the activity stream widget in PySide2 environments that's tied to this hide/show routine that's part of the widget's clear method. The change here is to only do that show/hide when Qt4 is in use, and to skip it otherwise.
One secondary change is that the activity stream widget now registers the task manager it's given with shotgun_globals. Since the widget makes use of shotgun_globals extensively, it should ensure that it has access to a background task manager.
> SG-6409: Doesn't hide/show the activity stream during a clear operation.

- python/activity_stream/activity_stream.py
- python/activity_stream/data_manager.py
Recent changes around how thumbnails behave when they are uploaded to Shotgun has resulted in a caching-related problem in the activity stream widget. The widget maintains a persistent sqlite cache, and includes the URLs for any thumbnails associated with items in the activity stream. If the cache contained a URL to a placeholder thumbnail, it would never be purged and the user would always see the placeholder instead of the "hero" thumbnail.
The fix is to detect the placeholder thumbnail when it's downloaded. When we do, we trigger a single-shot QTimer with a 20-second interval that dumps the cache and re-queries the activity stream data from Shotgun.
> SG-10692: Fix for placeholder thumb problems in the activity stream widget.

- docs/index.rst
Fix a small typo in the doc about how to use a widget form the framework.
> Documentation correction

- python/context_selector/context_widget.py
In tk-multi-publish2, the My Tasks context selector would not show Tasks assigned to a Group that the User belonged to. I modified the filter so that it would.
> Added HumanUser Group to the filters list for My Tasks

- python/context_selector/context_widget.py
If I try to select a Task in the context selection widget (for example in the Publisher) in an application using PySide2, it fails and my selection is cleared. Update the python code in order to work for both PySide and PySide2
> [SHOT-3163] Fix context selection with PySide2

- python/activity_stream/widget_activity_stream_base.py
- python/search_completer/hierarchical_search_completer.py
Simple fix, `filter` in Python 3 returns an iterator, not a list.
> SG-13278: ensures filter returns a list

- python/version_details/resources/version_details_widget.ui
- python/version_details/ui/version_details_widget.py
Removed the maximum height restriction on the title bar to fix a problem of the buttons being cut off in RV
> SG-18544 Title bar button size issue

- python/views/grouped_list_view/grouped_list_view.py
Handle the case when `_get_item_rect` is passed an invalid index or it is the root index -- this will create an empty `rows` list which will error on `rows[-1]`
> Bug Fix: GroupedListView bad index on _get_item_rect

- python/search_completer/search_result_delegate.py
This fixes an issue where global search results with a unicode character in them would completely fail to render. Now the result will be visible and selectable. However, due to the broader issue of incorrect unicode rendering in Toolkit in Python 2, the entry search results is going to keep garbled characters instead of the expected character, as can be seen in the screenshot below.
Note, the hierarchy search completer does not exhibit this bug and can properly match entries with unicode characters, so no fix was necessary.
Also, the rendering of unicode chars does not seem to be an issue in Python 3. 🙌
> SG-20166: global search unicode filter fix

- python/views/grouped_list_view/grouped_item_view.py
* Need to continue after selecting the group to ensure the y offset is updated to avoid selecting indexes that are not in the selection intersection
> Bug fix: Grouped item view selection

- python/filtering/filter_definition.py
* Filter names are built based on the entity display and field display names, but there are some cases where the name will be duplicated if the field display name already includes the entity name. In this case (where the entity name is already included in the field display), we will append the field name (not display name) in brackets
> SG-27819: Fix duplicate filter name

- python/delegates/view_item_delegate.py
- python/views/grouped_list_view/grouped_item_view.py
* Do not emit data changed signal on mouse move event, this is not necessary and causes the UI responsiveness to be slow (due to extra paint events being triggered)
* We cannot use the `roles` parameter to specify what data has changed when emitting the `dataChanged` signal since tk-core patches this method and ignores this parameter
* Fix method call
> SG-29407: Improve delegate handing of mouse mouse events.

- python/search_widget/search_widget.py
* Provide the option to listen for editing finished signal for whole text changes, instead of each new key stroke
* Update the `search_changed` signal to emit when the line edit sends the `editingFinished` signal
This change may help address this issue: https://community.shotgridsoftware.com/t/removing-the-search-widget-in-tk-multi-workfiles2/16478
> SearchWidget emit search changed signal on editing finished

- python/activity_stream/activity_stream.py
When a user does not have access to scripts, the activity stream contains references to note that this user does not have access to and it make qt-widget to crash. So I added a test to be sure that the current_user can access the note's Author to be sure there is no issue.
> SG-21292 Ensure the user has the permission to see the note's author

- python/context_selector/context_widget.py
* In some cases, like for custom entities, the context retrieved does not set the `name` on the entity data. This `name` field is expected, so an error occurs later when trying to display the selected entity if it has no name data
> Bug Fix:  Ensure context has entity name data, for the context widget

- python/filtering/filter_item_widget.py
- python/filtering/filter_menu.py
* Save and restore filters bug found in tk-multi-data-validation app
* Restore filters only after the filter definition has been fully rebuilt (else restore may fail if the filter definition does not exist yet)
> SHOT-4320:  Bug fix save and restore filters

- python/filtering/filter_menu.py
- python/utils.py
This PR addresses a bug encountered during the testing of the config v1.6.1-rc3 . This bug caused a SyntaxError in older versions of Houdini (17.5.460) and Nuke (12.0v8), which both still rely on Python 2.7.
> Config 1.6.1 RC3 - Linux - The Loader and the Shotgun panel fail to load and the Publishing does not work

- python/filtering/filter_item_widget.py
- python/filtering/filter_menu_group.py
* Add `sort_value` property to FilterItemWidget class to allow widgets to be sorted by their actual value (not by display value)
* This fixes displaying numeric filter widgets, where their value is numerical but display is a string representation (this caused numeric filters to be sorted like: 1, 11, 2, 22, 3, 4 instead of 1, 2, 3, 4, 11, 22)
> SHOT-4296: Sort filters when displayed in menu

- python/filtering/filter_menu.py
- tests/filtering/test_filter_menu.py
* Add missing '.' after fix for Python 2 syntax.
> Bug fix to get the correct field id from the search widget

- python/filtering/filter_item_widget.py
* To support PySide2, we must forward the signal state parameter as an int; however, this override the PySide6 patch to pass the state parameter as a QtCore.Qt.CheckState object
* The underlying issue is that the QtCore.Qt.CheckState object changed in PySide2 from a class object to an enum object. In PySide2, we could campare an int to the QtCore.Qt.CheckState, but this is no longer the case in PySide6
* To support both, we need to manually intercept the stateChanged signal and convert the state paramter to a QtCore.Qt.CheckState (even though this is already done in the pyside6 patcher)
> SG-34515 Fix forwarding signal to support both PySide2/6

- python/models/hierarchical_filtering_proxy_model.py
This is a workaround for the issue in Maya where it crashes when attempting to disconnect signals in the closeEvent method. It seems that the signals were already being disconnected. After handling the exception, the application's functionality remains unaffected.
> SG-34637 qt6  mac closing multi workfiles2 makes maya crash

- info.yml
#163 removes usages for `safe_delete_later` function, also removed on https://github.com/shotgunsoftware/tk-framework-shotgunutils/pull/155
We forgot to restrict the framework version requirements.
> SG-35731 Update required tk-framework-shotgunutils version

- python/filtering/filter_item_widget.py
If a task doesn't have a status set on SG, or tags, or the PublishedFile has no tags, they will be recognized as `None` in the breakdown2 component.
> This only happens when the user manually changes the PublishedFile version to `0` for their own purposes.
It seems it was working before this change: https://github.com/shotgunsoftware/tk-multi-breakdown2/pull/65. Adding @staceyoue as reviewer here.
|--|--|
|![image](https://github.com/user-attachments/assets/5fe8c72b-60c7-452a-adfd-22001a3bb32a) | ![image](https://github.com/user-attachments/assets/832fa4cb-efb5-41f7-a588-d2b75e98e74e)|
|--|--|
Using `six.ensure_str` breaks as it doesn't support a `None` type. This change attempts to fix this.
> SG-35973 Don't use ensure_str to prevent crashing
